<!DOCTYPE html>
<html lang="hu">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Színes feladat</title>
</head>
<body>
    <h1>Egyszerű piskóta</h1>
    <h2>Hozzávalók</h2>
<ul> <li>3 toás</li>
     <li>100g porcukor</li>
     <li>85g önkelő liszt</li>
</ul>
<h3>Megjegyzés a hozzávalókhoz</h3>
<dt>Porcukor</dt>
  <dd>Finomra darált fehér cukor</dd>
<dt>Önkelő liszt</dt>
  <dd>Előre elkészített liszt és kelesztő keverék (általaban hozzáadott sóval és élesztővel)</dd>
<h2>Elkészítés</h2>
<ol>
  <li>melegítsük elő a sütőt 190°C-ra</li>
  <li>Zsírozzunk be egy 20 cm-es kerek tortaformát</li>
  <li>Egy közepes méretű tálban keverjük habosra a tojásokat és a porcukrot</li>
  <li>Kerverjuk bele a lisztet</li>
  <li>Öntsük bele a keveréket az előkészített tortaformába</li>
  <li>Süssük 20 percig az előmelegített sütőben, amíg a tészta teteje könnyű nyomásra vissza nem ugrik</li> 
  <li>Hűtsük le a tortaformában az edényszárítón</li> 
</body>
</html>
